name: Deploy Backend to Droplet hehe
on:
  push:
    branches: [main]
jobs:
  jobOne:
    name: Deploying new push update to testing server
    runs-on: ubuntu-latest
    steps:
      - name: checking ssh connection
        uses: appleboy/ssh-action@master
        with:
          host: api.renteefy.ga
          username: root
          password: ${{ secrets.SERVER_SECRET }}
          port: 22
          script: |
            cd backend
            git checkout 0.0
            git pull
            npm install
            pm2 restart backendServer
